### ISSUE TITLE
NoClassDefFoundError in 8u60

### ISSUE THREAD

**Issue by hbrackmann** [TomasMikula/RichTextFX#155]
Caused by: java.lang.NoClassDefFoundError: com/sun/javafx/Utils
	at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:665)
	...
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.Utils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by TomasMikula** [comment]
Thanks for reporting. It is now fixed in 1.0.0-SNAPSHOT.
