### ISSUE TITLE
Exception when backspacing a single newline character

### ISSUE THREAD

**Issue by benedictleejh** [TomasMikula/RichTextFX#180]
I'm getting an exception when backspacing a single newline character in 0.6.8. Deleting a newline works, and so does having a newline in a selection and backspacing that.

The stack trace I'm getting is as follows:

```
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException
	at java.lang.Character.offsetByCodePoints(Character.java:5286)
	at org.fxmisc.richtext.EditActions.deletePreviousChar(EditActions.java:74)
	at org.fxmisc.richtext.skin.StyledTextAreaBehavior.deleteBackward(StyledTextAreaBehavior.java:292)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$null$23(EventHandlerTemplate.java:156)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$act$24(EventHandlerTemplate.java:155)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate$Builder.lambda$create$21(EventHandlerTemplate.java:117)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$17(EventHandlerTemplate.java:39)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$15(EventHandlerTemplate.java:26)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$19(EventHandlerTemplate.java:49)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$15(EventHandlerTemplate.java:26)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$15(EventHandlerTemplate.java:26)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$15(EventHandlerTemplate.java:26)
	at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$bind$14(EventHandlerTemplate.java:18)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:197)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:147)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$354(GlassViewEventHandler.java:228)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:227)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

I am using a custom `InlineStyleTextArea`, though that doesn't seem to be the issue, seeing as it isn't throwing in my code.

Also, 0.6.7 doesn't have the issue, so I've downgraded to that for now.

**Comment by melkhaldi** [comment]
try 0.6.9, Tomas just released it. I believe it fixes the backspace issue.

**Comment by benedictleejh** [comment]
I apologise for not having seen the earlier issue regarding this, and raising an already solved issue. As such I am closing this issue.

I am however, remaining on 0.6.7, because of incompatible UndoFX versions with 0.6.9 and my project.

**Comment by melkhaldi** [comment]
What is the compatibility issue with UndoFX and your project? it is
probably good report it, maybe there is a workaround.

v0.6.9 also adds copy paste text with styles, which is great-- previous
versions support copy/paste of only text strings, no styles are carried
through.

**Comment by benedictleejh** [comment]
It's more of an internal issue with my project. UndoFX 1.2 (which 0.6.9 requires) uses a new API that requires changes be directly invertible. For my project this is not possible without a lot of refactoring in my change types due to some changes causing a cascade of things that must also be changed, and are thus not directly invertible.

**Comment by TomasMikula** [comment]
Hi Benedict, I would be interested in your use case. I didn't think that inverting a change would be a big deal. For example for text changes it is just [swapping the removed and inserted fields](https://github.com/TomasMikula/RichTextFX/blob/ec2b92945a74cdd8b8994c20fe587138631225e3/richtextfx/src/main/java/org/fxmisc/richtext/TextChange.java#L21).

**Comment by benedictleejh** [comment]
Hi Tomas, I'll try to explain what I'm doing with UndoFX as best I can. I have a set of nodes, and each node can contain rules that reference other nodes. The application is divided into layers, approximating a client-server model (without actually having client and server processes), and layers communicate via an event bus. All actions to be taken are triggered via events. I also have a plugin system which hooks into the application via triggers that get executed when certain events happen.

Events are granular because of the plugin system; I need to inform plugins exactly what has changed, so they can figure out what to do. And the undo manager uses the event bus to execute the actions it needs to take as well, i.e. it does not have direct access to the data structures it needs to change. For example:

```scala
class NodeCreatedChange(createdNode: Node) extends Undoable {
  override def undo(): Unit = UndoEventDispatcher.destroyNode(createdNode)
  override def redo(): Unit = UndoEventDispatcher.createNode(createdNode)
}
```

We can see that while `undo` and `redo` are inverse actions of each other, they don't do exactly the same thing, so this change is not invertible. And the action to perform is not a direct modification of the data structure involved, instead firing an event that results in the action to be performed.

Because nodes contain rules that reference other nodes, node destruction requires that I remove all rules that reference the node to be destroyed, resulting in updating a bunch of other nodes. So the node destruction change, and node creation change are not inverses of each other either.

**Comment by TomasMikula** [comment]
Hi Benedict, thanks for sharing. What about this?

```scala
sealed trait NodeChange {
  def apply(): Unit
  def invert(): NodeChange
}

case class NodeCreated(node: Node) extends NodeChange {
  override def apply() = UndoEventDispatcher.createNode(node)
  override def invert() = NodeDestroyed(node)
}

case class NodeDestroyed(node: Node) extends NodeChange {
  override def apply() = UndoEventDispatcher. destroyNode(node)
  override def invert() = NodeCreated(node)
}
```

**Comment by benedictleejh** [comment]
That, unfortunately, doesn't quite work. This is my current full node destruction change:

```scala
class NodeDestroyedChange(destroyedNode: Node, changedNodes: Map[Node, Node]) extends Undoable {
  override def undo(): Unit = {
    UndoEventDispatcher.createNode(destroyedNode)
    changedNodes foreach { case (unedited, edited) =>
      UndoEventDispatcher.updateNode(edited, unedited)
    }
  }

  override def redo(): Unit = UndoEventDispatcher.destroyNode(destroyedNode)
}
```

Destruction causes a potential bunch of updates in every other node, because nodes can have rules that reference other nodes. On creation this isn't an issue, because a non-existent node can't be referenced. But before destruction, other nodes may have been updated to have rules that reference the node to be destroyed.
