### ISSUE TITLE
NoSuchMethodError: org.reactfx.Suspendable.suspendWhen(Ljavafx/beans/value/ObservableValue;)Lorg/reactfx/Subscription

### ISSUE THREAD

**Issue by euwbah** [TomasMikula/RichTextFX#261]
Here's the error message:

```
"C:\Program Files (x86)\Java\jdk1.8.0_20\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:3715,suspend=y,server=n -javaagent:C:\Users\Matthew_Tan\.IdeaIC14\system\groovyHotSwap\gragent.jar -Dfile.encoding=windows-1252 -classpath "C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\jfxswt.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_20\jre\lib\ext\zipfs.jar;C:\Users\Matthew_Tan\IDEAProjectsJava\MuseLang\build\classes\main;C:\Users\Matthew_Tan\IDEAProjectsJava\MuseLang\build\resources\main;C:\Users\Matthew_Tan\.gradle\caches\modules-2\files-2.1\org.fxmisc.richtext\richtextfx\1.0.0-SNAPSHOT\f04840eaa74ea5641b68e0d6c251824b22de992d\richtextfx-1.0.0-SNAPSHOT.jar;C:\Users\Matthew_Tan\.gradle\caches\modules-2\files-2.1\org.fxmisc.flowless\flowless\0.5-SNAPSHOT\931a58df43b4a2f5b1589e9d4a11b70c4f2da5f9\flowless-0.5-SNAPSHOT.jar;C:\Users\Matthew_Tan\.gradle\caches\modules-2\files-2.1\org.fxmisc.undo\undofx\1.2\73c7ab2672ff3c32daa0e82e61554840ba7290bd\undofx-1.2.jar;C:\Users\Matthew_Tan\.gradle\caches\modules-2\files-2.1\org.fxmisc.wellbehaved\wellbehavedfx\0.1.1\bb43719bbc27439d7ab6164b7a75dfcb7e651d7e\wellbehavedfx-0.1.1.jar;C:\Users\Matthew_Tan\.gradle\caches\modules-2\files-2.1\org.reactfx\reactfx\2.0-M4u1\c48f5055fc1295a90edbe753a8c9fc3869fd046f\reactfx-2.0-M4u1.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 14.1.5\lib\idea_rt.jar" MuseLangEnvironment
Connected to the target VM, address: '127.0.0.1:3715', transport: 'socket'
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:363)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:875)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$147(LauncherImpl.java:157)
	at com.sun.javafx.application.LauncherImpl$$Lambda$48/25372969.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.reactfx.Suspendable.suspendWhen(Ljavafx/beans/value/ObservableValue;)Lorg/reactfx/Subscription;
	at org.fxmisc.richtext.StyledTextAreaModel.<init>(StyledTextAreaModel.java:357)
	at org.fxmisc.richtext.StyledTextArea.<init>(StyledTextArea.java:508)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:14)
	at org.fxmisc.richtext.StyleClassedTextArea.<init>(StyleClassedTextArea.java:27)
	at org.fxmisc.richtext.CodeArea.<init>(CodeArea.java:28)
	at MuseLangEnvironment.start(MuseLangEnvironment.java:28)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$153(LauncherImpl.java:821)
	at com.sun.javafx.application.LauncherImpl$$Lambda$51/14952804.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$166(PlatformImpl.java:323)
	at com.sun.javafx.application.PlatformImpl$$Lambda$44/25384360.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/9831426.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$46/33168795.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
	at com.sun.glass.ui.win.WinApplication$$Lambda$37/12489389.run(Unknown Source)
	... 1 more
Exception running application MuseLangEnvironment
Disconnected from the target VM, address: '127.0.0.1:3715', transport: 'socket'

Process finished with exit code 1

```
Here's the code that causes it:
CodeArea c = new CodeArea();

Well... what is going on... o..o

**Comment by euwbah** [comment]
Should it be `suspendWhile()`??

**Comment by TomasMikula** [comment]
Hi, the snapshot version that you have on your classpath (`richtextfx-1.0.0-SNAPSHOT`) [uses `reactfx-2.0-SNAPSHOT`](https://github.com/TomasMikula/RichTextFX/blob/b2f3c74e93a791bbf3dbe37fcf9edeac6c2ba8a5/richtextfx/build.gradle#L7). But on your classpath, you have `reactfx-2.0-M4u1`. The `suspendWhen` has only been added recently and is not present in that version of ReactFX.

**Comment by euwbah** [comment]
I see. Is it necessary to use the snapshot versions for all the required libraries, or would reactfx just do fine? (Also, if I were to use snapshots for all the libraries, would there be severe bugs?).

**Comment by euwbah** [comment]
Anyways, it's all working properly now :) Thanks!

**Comment by JordanMartinez** [comment]
> Is it necessary to use the snapshot versions for all the required libraries, or would reactfx just do fine? 

The Snapshot versions are for ReactFX and Flowless. ReactFX needs the snapshot so that #189 gets fixed, among other things. Flowless needed the snapshot so that #213 was possible, among other things. Fortunately, they don't have any bugs that we know of. 

Tomas needs to make a new release for both of them, but it seems he has decided to wait until we finish any other updates or new features for RichTextFX that would then invalidate such releases. So, when everything is good to go for `0.7.0`, Tomas will probably release new releases for those two libraries, then update the `build.gradle` file here to use those new releases, and then release `0.7.0`.

**Comment by euwbah** [comment]
Ahh I see!
