### ISSUE TITLE
NullPointerException after aborted text drag ?

### ISSUE THREAD

**Issue by Jugen** [TomasMikula/RichTextFX#320]
Hi Tomas

I'm not sure exactly when or why this exception occurs but it seems to appear quite often in my user's logs in production. I think it happens when a view is closed and removed from the scene ?
The actual exception seems to be thrown by FX though in Node.screenToLocal. Is there some way to prevent this from happening ?

Edit:  Ok, so I've been able to reproduce it now .... if a user selects some text and then clicks and drags it outside the control (preferably out of the app), then releases the click, and closes the view (like a tab) containing the RichText box then the NPE is repeatedly thrown over & over continuously.

It would seem then that drag "canceled" is not properly detected (in StyledTextAreaBehavior?) because the mouse click was released outside of the control ?

Thanks, regards
Jurgen

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.scene.Node.screenToLocal(Unknown Source)
	at org.fxmisc.richtext.skin.ParagraphBox.hit(ParagraphBox.java:134)
	at org.fxmisc.richtext.skin.ParagraphBox.hit(ParagraphBox.java:129)
	at org.fxmisc.richtext.skin.StyledTextAreaView.hit(StyledTextAreaVisual.java:361)
	at org.fxmisc.richtext.skin.StyledTextAreaBehavior.dragTo(StyledTextAreaBehavior.java:477)
	at org.reactfx.value.Val.ifPresent(Val.java:142)
	at org.fxmisc.richtext.skin.StyledTextAreaBehavior.lambda$new$113(StyledTextAreaBehavior.java:255)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$201(MappedStream.java:22)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EmitBothOnEachStream.lambda$observeInputs$182(EmitBothOnEachStream.java:28)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.MappedStream.lambda$observeInputs$201(MappedStream.java:22)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.AccumulatingStream.lambda$observeInputs$157(AccumulatingStream.java:31)
	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$272(NotificationAccumulator.java:134)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
	at org.reactfx.EventStreams$16$1.handle(EventStreams.java:340)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$485(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(Unknown Source)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$405(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by TomasMikula** [comment]
Hi Jugen,

> It would seem then that drag "canceled" is not properly detected (in StyledTextAreaBehavior?) because the mouse click was released outside of the control ?

That would seem like a probable cause to me as well. However, I cannot reproduce this on Mac with JDK 1.8.0_92, either with richtextfx-0.6.10, or with the current HEAD of the master branch. This is the test case I tried 

```java
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.stage.Stage;

import org.fxmisc.richtext.StyleClassedTextArea;

public class TabTest extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        StyleClassedTextArea area = new StyleClassedTextArea();
        area.setWrapText(true);

        TabPane tp = new TabPane(new Tab("hello", area));

        Scene scene = new Scene(tp, 600, 400);
        primaryStage.setScene(scene);
        primaryStage.show();

        area.requestFocus();
    }

}
```

Insert a long text, drag a piece outside of the window and then close the tab. I didn't get any exception. Can you try this as well?

**Comment by TomasMikula** [comment]
I believe even without running it that this reproduces your problem, but this is not RichTextFX's problem. Doesn't `tp.setCollapsible(false)` work for you?

**Comment by Jugen** [comment]
Hi Tomas

The problem that I had with `tp.setCollapsible(false)` is that it disables the animation for `tp.setExpanded( T/F )`

My use case is that I don't want the user to be able to directly collapse the TitledPane but I do want to be able to do it via code, and it must be animated.

Anyway I have now removed the event filter and refactored my code to switch collapsible on just before `tp.setExpanded( T/F )` and then off again after the animation finishes. Tedious but it works.

Thanks for looking into this for me.
