### ISSUE TITLE
Spamming Ctrl+Z makes the JavaFXApplication crash 

### ISSUE THREAD

**Issue by AlisCode** [TomasMikula/RichTextFX#358]
Hi, 

Im using RichTextFX's CodeArea and noticed a weird bug.

Basically every shortcut works as expected : Ctrl+C, Ctrl+V... But spamming Ctrl+Z makes the JavaApplication crash. 
 
Windows 10 x64, coding with NetBeans.
I'm using the RichTextFX FatJar version 0.6.10 

Error code :
Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Unexpected change received.
Expected:
org.fxmisc.richtext.PlainTextChange@745f
Received:
org.fxmisc.richtext.PlainTextChange@74c3
        at org.fxmisc.undo.impl.UndoManagerImpl.changeObserved(UndoManagerImpl.java:185)
        at org.reactfx.util.QueuingStreamNotifications.lambda$head$274(NotificationAccumulator.java:217)
        at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
        at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
        at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
        at org.reactfx.MultiGuard.close(Guard.java:83)
        at org.fxmisc.richtext.StyledTextArea.replace(StyledTextArea.java:731)
        at org.fxmisc.richtext.StyledTextArea.replaceText(StyledTextArea.java:718)
        at org.fxmisc.richtext.TextEditingArea.replaceText(TextEditingArea.java:204)
        at org.fxmisc.richtext.EditActions.replaceSelection(EditActions.java:119)
        at org.fxmisc.richtext.skin.StyledTextAreaBehavior.keyTyped(StyledTextAreaBehavior.java:281)
        at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$null$23(EventHandlerTemplate.java:156)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.fxmisc.wellbehaved.event.EventHandlerTemplate$On.lambda$act$24(EventHandlerTemplate.java:155)
        at org.fxmisc.wellbehaved.event.EventHandlerTemplate$Builder.lambda$create$21(EventHandlerTemplate.java:117)
        at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$null$17(EventHandlerTemplate.java:39)
        at org.fxmisc.wellbehaved.event.EventHandlerTemplate.lambda$bind$14(EventHandlerTemplate.java:18)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
        at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
        at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:216)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:148)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$353(GlassViewEventHandler.java:247)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:246)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
        at com.sun.glass.ui.View.notifyKey(View.java:966)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)

Any fix ?

**Comment by JordanMartinez** [comment]
> Unexpected change received.
> Expected:
> org.fxmisc.richtext.PlainTextChange@745f
> Received:
> org.fxmisc.richtext.PlainTextChange@74c3

It's not the spamming of Ctrl+Z that's the issue. 

UndoFX works like so:

1. The UndoManager gets notified every time the editable object gets changed. When it does, it stores that change in a queue.
2. When the user undos/redos a change, the UndoManager will store that change before applying it. By applying that change, the UndoManager now gets notified of the change. However, in this case, the received change is not a new one, so it should ignore it. It knows this by compares the change it received with the one it expected (the one it stored in a variable before applying it). If they equal (`a.equals(b)`), then it does not add the received change to its queue since it's already in there. The position that points to the next redoable redo and undoable undo gets incremented forward by one.
3. The issue you are experiencing arises when a unique situation happens: the user calls undo/redo, the change to be applied is stored away for comparison for later, and the change is applied. However, the applied change does not get emitted as a notification to the UndoManager. (I forget the exact reasons why....). When the user applies a change, the UndoManager goes through the normal steps: check if the `expectedChange` is null (this is a new change): false; check if the received change equals the `expectedChange` (this is a redone/undone change): false, because the previous change was never cleared out of `expectedChange`; default to third case: throw your above exception.

We might have fixed this in the latest `0.7` release, but I can't remember. Could you compare the `0.6.10In case you can't update to the newest release, I think, but am not entirely sure, you can backport [the fix we implemented for that](https://github.com/TomasMikula/RichTextFX/blob/master/richtextfx/src/main/java/org/fxmisc/richtext/model/EditableStyledDocument.java#L46-L52)

**Comment by TomasMikula** [comment]
This might be the same issue as #322.

**Comment by TomasMikula** [comment]
If you can try 0.7-M2, if it doesn't solve the problem, it should at least give a better error message.

**Comment by JordanMartinez** [comment]
> This might be the same issue as #322.

Mm... I thought we had addressed this elsewhere...

**Comment by eliottizi** [comment]
Ok it's working well since the 0.7 thanks a lot for your reactivity !
